tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "sanemat/font"
brew "openssl"
brew "readline"
brew "autoconf"
brew "automake"
brew "xz"
brew "awscli"
brew "bash"
brew "coreutils"
brew "colordiff"
brew "ctop"
brew "docker", link: false
brew "libyaml"
brew "docker-compose", link: false
brew "flyway"
brew "gettext"
brew "git"
brew "git-flow"
brew "libtool"
brew "graphviz"
brew "htop"
brew "hub"
brew "iftop"
brew "luajit"
brew "msgpack"
brew "mysql@5.7", link: true
brew "mecab"
brew "nkf"
brew "unibilium"
brew "vim"
brew "pkg-config"
brew "protobuf"
brew "reattach-to-user-namespace"
brew "redis"
brew "sanemat/font/ricty", args: ["with-powerline"]
brew "terraform"
brew "tig"
brew "tmux"
brew "wget"
brew "zlib"
brew "zsh"
brew "jq"
brew "kubernetes-cli", link: false
brew "kustomize"
brew "stern"
cask "docker"
cask "google-cloud-sdk"
